
title: Cult of Dave

description: >- # this means to ignore newlines until "baseurl:"
  The Cult of Dave is a group of people who play Mage: The Ascension, a tabletop role-playing game,
  live on the Chaotic Neutral Games Twitch channel. This site has information pertaining to that game
  and others. All hail Dave!
collections:
  cloud-gate:
    output: true
    colour: purple
    header-style: dark
    permalink: /:collection/:title/

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cultofdave.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
plugins:
  - jekyll-seo-tag
highlighter: rouge

kramdown:
  parse_block_html: true